name: "Service: Mongo"
description: "Sets up a Mongo DB service for testing purposes."
runs:
  using: "composite"
  steps:
    - name: "Configure MongoDB Hostname"
      run: |
        sudo echo "127.0.0.1 mongo" | sudo tee -a /etc/hosts
      shell: bash

    - name: "Start MongoDB"
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '4.4'
