name: "Slack Notify"
description: "Send a notification to Slack. Used to signal successful builds and deployments."
inputs:
  event:
    description: "The 'event' for which we are notifying: ['build','deploy']"
    required: true
  webhook_url:
    description: "The Slack webhook for your workspace."
    required: true
  success:
    description: "The status of the build pipeline. Expects a stringy boolean: ['true', 'false']"
    required: true
  image_tag:
    description: "An associated image tag with which to report back to Slack."
    required: false
  steps:
    description: "An array of step ids that failed."
    required: false
  matrix:
    description: "The value of matrix.*, if the step is being ran for multiple values. This is to differentiate the output."
    required: false
runs:
  using: "composite"
  steps:


    - name: "Build Success"
      if: ${{ inputs.event == 'build' && inputs.success == 'true' }}
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: 'G3184HDT6' # CICD
        payload: |
          {
            "attachments": [
              {
                "color": "#2eb886",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*${{github.event.repository.name}}*: Build <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}> by ${{github.actor}} successful! :ok_hand:"
                    }
                  },
                  { "type": "divider" },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ${{ toJSON(github.event.head_commit.message) || 'No commit message' }}
                    },
                    "accessory": {
                      "type": "image",
                      "image_url": "https://popcat.click/twitter-card.jpg",
                      "alt_text": "Nice!"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": ":github: *Repository*: <${{ github.server_url }}/${{ github.repository}}|${{ github.repository }}>\n:git: *Ref*: ${{ github.ref_name}}\n:1234: *Build Number*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}>\n:docker: *Image Tag*: ${{inputs.image_tag}}\n:matrix-parrot: ${{inputs.matrix}}\n:ladder: ${{inputs.steps}}"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: "Build Failure"
      if: ${{ inputs.event == 'build' && inputs.success != 'true' }}
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: 'G3184HDT6' # CICD
        payload: |
          {
            "attachments": [
              {
                "color": "#a30200",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*${{github.event.repository.name}}*: Build <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}> by ${{github.actor}} failed! :scream::cry:"
                    }
                  },
                  { "type": "divider" },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Build failed on the ${{ inputs.matrix != '' && format('matrix value {0},', inputs.matrix) }} ${{ inputs.steps }} step."
                    },
                    "accessory": {
                      "type": "image",
                      "image_url": "https://www.meme-arsenal.com/memes/aaf82c28cdb84f5ab79dd8eb460c1d11.jpg",
                      "alt_text": "Oof."
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: "Deployment Notification"
      if: inputs.event == 'deploy'
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: 'G3184HDT6' # CICD
        payload: |
          {
            "attachments": [
              {
                "color": "${{ inputs.success == 'true' && '#2eb886' || '#a30200' }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*${{ inputs.success == 'true' && 'Deployment Success' || 'Deployment Failure' }}: ${{github.event.repository.name}}*"
                    }
                  },
                  { "type": "divider" },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Deployment <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}> of image ${{inputs.image_tag}} to *${{github.ref_name}}* ${{ inputs.success == 'true' && 'successful' || 'failed' }}! ${{ inputs.success == 'true' && ':kubernetes::100::peepo_clap:' || ':scream::pepetrashscared:' }}"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

