name: 'Git'
description: 'Configure Git access to private repositories via either SSH key or HTTPS PAT'
inputs:
  git_type:  # id of input
    description: 'Whether to use `SSH` or `HTTPS`'
    required: true
    default: 'SSH'
  git_key:
    description: 'Either the SSH key or HTTPS PAT to setup'
runs:
  using: "composite"
  steps:
    ################################################################################
    # SSH Key Steps                                                                #
    ################################################################################
    - name: "SSH Keyscan"
      if: ${{ inputs.git_type == 'SSH' }}
      id: scan
      run: echo "::set-output name=known_hosts::$(ssh-keyscan -t rsa github.com)"
      shell: bash

    - name: "SSH Key Install"
      if: ${{ inputs.git_type == 'SSH' }}
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.git_key }}
        name: id_rsa
        known_hosts: ${{ steps.scan.outputs.known_hosts }}
        if_key_exists: replace

    - name: "Git Config" # Issue an HTTPS -> Git override for VCS repositories
      if: ${{ inputs.git_type == 'SSH' }}
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com"          

    ################################################################################
    # HTTPS PAT Steps                                                              #
    ################################################################################
    - name: "Git Config" # Issue an HTTPS -> Git override for VCS repositories
      if: ${{ inputs.git_type == 'HTTPS' }}
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com"  
# TODO: Change this appropriately