name: "CLI Build"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Git HTTPS"
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: "Setup Deps"
        run: |
          make dependencies

      - name: "Build"
        env:
          GOPRIVATE: github.com/linc-technologies
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make

      - name: "Test"
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make test
