name: "CLI Build"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: "Setup Deps"
        run: |
          make dependencies

      - name: "Build"
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make

      - name: "Test"
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make test
