name: "CLI Build"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
      GOPRIVATE: github.com/linc-technologies
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

      - name: "Git HTTPS"
        id: git_https
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      - name: "Setup Go"
        id: setup_go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: "Format"
        id: format
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            gofmt -l .
            exit 1; 
          fi

      - name: "Setup Deps"
        id: setup_deps
        run: |
          make dependencies

      - name: "Build"
        id: build
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make

      - name: "Test"
        id: test
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make test
