name: "CLI Release"

on:
  workflow_call:

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v3

      - name: "Tags"
        run: git fetch --tags origin

      - name: "Git HTTPS"
        id: git_https
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      - name: "Setup Go"
        id: setup_go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: "Run GoReleaser"
        id: run_goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
