name: "CLI Build"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v2

      - name: "Git HTTPS"
        id: git_https
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      - name: "Setup Go"
        id: setup_go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: "Format"
        id: format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: "Setup Deps"
        id: setup_deps
        run: |
          make dependencies

      - name: "Build"
        id: build
        env:
          GOPRIVATE: github.com/linc-technologies
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make

      - name: "Test"
        id: test
        run: |
          export PATH=$HOME/bin/:$GOPATH/bin/:$PATH
          make test
