name: "Go"

on:
  workflow_dispatch:
  workflow_call:

env:
  CONTAINER_REGISTRY: linced.azurecr.io/linc-ed

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:


      - name: "Pass"
        id: pass
        run: exit 0

      - name: "Fail"
        id: fail
        run: exit 1

      - name: "Slack Notify"
        if: success() || failure()
        run: |
          echo ${{ steps.pass.outcome }}
          echo ${{ steps.fail.outcome }}
          echo ${{ steps.*.outcome }}
          echo ${{ toJSON(steps) }}
          

      - name: "Slack Notify"
        if: success() || failure()
        uses: linc-technologies/.github/.github/actions/slack_notify@master
        continue-on-error: true
        with:
          event: build
          # Success only works in if conditionals
          # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
          success: success()
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
