name: "Go"

on:
  workflow_dispatch:
  workflow_call:

env:
  CONTAINER_REGISTRY: linced.azurecr.io/linc-ed

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      build_num: ${{ steps.tag.outputs.build_num }}
      image_tag_build: ${{ steps.tag.outputs.image_tag_build }}
      image_tag_branch: ${{ steps.tag.outputs.image_tag_branch }}
    steps:

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Git HTTPS"
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
#          cache: true $ TODO: Throwing issues with repeat builds....

      # Run build of the application
      - name: Run build
        env:
          GOPRIVATE: github.com/linc-technologies
          CGO_ENABLED: 0
        run: |
          cd ./cmd/${{ github.event.repository.name }}/
          go build -tags internal -ldflags="-s -w" -v

      - name: "Setup Mongo"
        if: github.event.repository.name != 'finance'
        uses: linc-technologies/.github/.github/actions/service_mongo@feature/composite

      - name: "Setup MySQL"
        if: github.event.repository.name == 'finance'
        uses: linc-technologies/.github/.github/actions/service_mysql@feature/composite



      # Run testing on the code
      - name: Run testing
        run: go test -vet=off -tags internal -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # TODO: Create a new workflow for dependabot with only composite actions to limit steps like these
      - name: Login to ACR
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v2
        with:
          registry: linced.azurecr.io
          username: ${{ secrets.AZURE_ACR_LINCED_USERNAME }}
          password: ${{ secrets.AZURE_ACR_LINCED_PASSWORD }}

      - name: "Export build tag"
        id: tag
        env:
          BUILD: ${{ github.run_number }}
        run: |
          echo "::set-output name=build_num::$(($BUILD+10000))"
          echo "::set-output name=image_tag_build::${{env.CONTAINER_REGISTRY}}/${{ github.event.repository.name }}:$(($BUILD+10000))"
          echo "::set-output name=image_tag_branch::${{env.CONTAINER_REGISTRY}}/${{ github.event.repository.name }}:${{github.ref_name}}"

      - name: "Build and export to Docker"
        uses: docker/build-push-action@v3
        if: ${{ !contains(fromJson('["development", "staging", "production"]'), github.ref_name) }}
        id: push_build_tag
        with:
          context: .
          push: false
          tags: ${{ steps.tag.outputs.image_tag_build }}
          file: Dockerfile.drone

      - name: "Build and export to Docker (Environment Based)"
        uses: docker/build-push-action@v3
        if: contains(fromJson('["development", "staging", "production"]'), github.ref_name)
        id: push_build_and_env_tag
        with:
          context: .
          push: true
          tags: |
            ${{ steps.tag.outputs.image_tag_build }}
            ${{ steps.tag.outputs.image_tag_branch }}
          file: Dockerfile.drone

      - name: "Slack Notify"
        if: success() || failure()
        uses: linc-technologies/.github/.github/actions/slack_notify@feature/composite
        with:
          event: build
          success: success()
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    name: "Deploy"
    if: contains(fromJson('["development", "staging", "production"]'), github.ref_name)
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      # Install Kubectl
      - name: Configure Kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.22.6'

      # If we're deploying from a non-production branch, configure Kubectl with Dev cluster secrets
      - name: "Kubernetes Auth (Dev AU East)"
        if: ${{ github.ref  != 'refs/heads/production' }}
        run: |
          kubectl config set-credentials default --token=${{ secrets.DEVELOPMENT_AU_EAST_AKS_TOKEN }}
          # If cert provided...
          # kubectl config set-cluster default --server=${{ secrets.DEVELOPMENT_AU_EAST_AKS_SERVER }} --certificate-authority=ca.crt
          # If cert not provided
          kubectl config set-cluster default --server=${{ secrets.DEVELOPMENT_AU_EAST_AKS_SERVER }} --insecure-skip-tls-verify=true
          kubectl config set-context default --cluster=default --user=default
          kubectl config use-context default

      # If we're deploying from a production branch, configure Kubectl with Prod cluster secrets
      - name: "Kubernetes Auth (Prod AU East)"
        if: ${{ github.ref == 'refs/heads/production' }}
        run: |
          kubectl config set-credentials default --token=${{ secrets.PRODUCTION_AU_EAST_AKS_TOKEN }}
          # If cert provided...
          # kubectl config set-cluster default --server=${{ secrets.PRODUCTION_AU_EAST_AKS_SERVER }} --certificate-authority=ca.crt
          # If cert not provided
          kubectl config set-cluster default --server=${{ secrets.PRODUCTION_AU_EAST_AKS_SERVER }} --insecure-skip-tls-verify=true
          kubectl config set-context default --cluster=default --user=default
          kubectl config use-context default

      # Showcase the client and server Kubectl versions
      - run: kubectl version

      # Deploy specific container revision
      - name: "Kubernetes Deploy"
        env:
          CONTAINER: ${{ github.event.repository.name }}
          DEPLOYMENT: ${{ github.event.repository.name }}-deployment
          NAMESPACE: ${{ github.ref_name }}
          IMAGE: ${{ needs.build.outputs.image_tag_build }}
        run: |
          echo "Updating $CONTAINER in $DEPLOYMENT to $IMAGE in the $NAMESPACE namespace."
          kubectl set image deployment/$DEPLOYMENT  $CONTAINER=$IMAGE --record=true --namespace=${NAMESPACE}

      - name: "Slack Notify"
        if: success() || failure()
        uses: linc-technologies/.github/.github/actions/slack_notify@feature/composite
        with:
          event: deploy
          success: success()
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

