name: "Go"

on:
  workflow_dispatch:
  workflow_call:


# TODO: Complete these
# GoLang steps:
# ✅       cachePrime,
# ✅       cacheRestore,
# ✅       ciDep,
# ✅       ciTest,
# ✅       slackUnitTests,
# ✅       compile,
# ✅       cacheRebuild,
# ✅       dockerBuild,
# ✅       slackBuild,
# ✅       deployKubernetes,
# ❌       deployHelm,
# ✅       slackDeploy,

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    name: "Build"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
          cache: true

      # Perform a key-scan of 'bitbucket.org' and register the output for the SSH key step below
      - name: BitBucket Keyscan
        id: scan
        run: echo "::set-output name=known_hosts::$(ssh-keyscan -t rsa bitbucket.org)"

      # Install an SSH key for BitBucket authentication
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BITBUCKET_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ steps.scan.outputs.known_hosts }}
          if_key_exists: replace

      # Issue an HTTPS -> Git override for BitBucket and GitHub repositories
      - name: Git Config
        run: |
          git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org"          
          git config --global url."git@github.com:".insteadOf "https://github.com"          

      # Install all the dependencies
      - name: Install dependencies
        env:
          GOPRIVATE: github.com
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # Debug repo name
      - name: Debug
        run: |
          env | grep -i GITHUB

      # Run build of the application
      - name: Run build
        env:
          GOPRIVATE: github.com
        run: |
          cd ./cmd/${{ github.event.repository.name }}/
          go build -tags development -ldflags="-s -w" -v

# TODO: Change this to CD to a valid directory, ensure it will not cause widespread breaks
#      # Run vet & lint on the code
#      - name: Run vet & lint
#        run: |
#          go vet .
#          golint .

      # Test code expects to access mongo @ `mongo` per previous build system
      - name: Mongo Hostname
        run:
          sudo echo "127.0.0.1 mongo" | sudo tee -a /etc/hosts

      # Start a Mongo DB server for testing
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      # Run testing on the code
      - name: Run testing
        run: go test -vet=off -tags internal -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: linced.azurecr.io
          username: ${{ secrets.AZURE_ACR_LINCED_USERNAME }}
          password: ${{ secrets.AZURE_ACR_LINCED_PASSWORD }}

      - name: Bump build number
        id: num
        env:
          BUILD: ${{ github.run_number }}
        run: |
          echo "::set-output name=build_num::$(($BUILD+10000))"

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        id: push
        with:
          context: .
          push: true
          tags: linced.azurecr.io/linced/${{ github.event.repository.name }}:${{ steps.num.outputs.build_num }}
          file: Dockerfile.drone

  notify_build:
    name: "Notify Build"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deployment Notification
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: 'G3184HDT6' # CICD
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  deploy:
    name: "Deploy"
    if: contains(["development", "staging", "production"], github.ref_name)
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      # Install Kubectl
      - name: Configure Kubectl
        uses: azure/setup-kubectl@v2.0


      # If we're deploying from a non-production branch, configure Kubectl with Dev cluster secrets
      - name: Kubernetes Auth (Dev AU East)
        if: ${{ github.ref  != 'refs/heads/production' }}
        run: |
          kubectl config set-credentials default --token=${{ secrets.DEVELOPMENT_AU_EAST_AKS_TOKEN }}
          # If cert provided...
          # kubectl config set-cluster default --server=${{ secrets.DEVELOPMENT_AU_EAST_AKS_SERVER }} --certificate-authority=ca.crt
          # If cert not provided
          kubectl config set-cluster default --server=${{ secrets.DEVELOPMENT_AU_EAST_AKS_SERVER }} --insecure-skip-tls-verify=true
          kubectl config set-context default --cluster=default --user=default
          kubectl config use-context default

      # If we're deploying from a production branch, configure Kubectl with Prod cluster secrets
      - name: Kubernetes Auth (Prod AU East)
        if: ${{ github.ref == 'refs/heads/production' }}
        run: |
          kubectl config set-credentials default --token=${{ secrets.PRODUCTION_AU_EAST_AKS_TOKEN }}
          # If cert provided...
          # kubectl config set-cluster default --server=${{ secrets.PRODUCTION_AU_EAST_AKS_SERVER }} --certificate-authority=ca.crt
          # If cert not provided
          kubectl config set-cluster default --server=${{ secrets.PRODUCTION_AU_EAST_AKS_SERVER }} --insecure-skip-tls-verify=true
          kubectl config set-context default --cluster=default --user=default
          kubectl config use-context default

      # Showcase the client and server Kubectl versions
      - run: kubectl version

      # Deploy specific container revision
      - name: Kubernetes Deploy
        env:
          CONTAINER: ${{ github.event.repository.name }}
          DEPLOYMENT: ${{ github.event.repository.name }}-deployment
          NAMESPACE: ${{ github.ref_name }}
          IMAGE: linced.azurecr.io/linced/${{ github.event.repository.name }}:${{ steps.num.outputs.build_num }}
        run: |
          echo "Updating $CONTAINER in $DEPLOYMENT to $IMAGE in the $NAMESPACE namespace."
          kubectl set image deployment/$DEPLOYMENT  $CONTAINER=$IMAGE --record=true


  notify_deploy:
    name: "Notify Deployment"
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Deployment Notification
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: 'G3184HDT6' # CICD
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action deployment result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action deployment result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK