name: "Go"

on:
  workflow_dispatch:
  workflow_call:

env:
  CONTAINER_REGISTRY: linced.azurecr.io/linc-ed

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

      - name: "Fail"
        run: exit 1

      - name: "Slack Notify"
        if: success() || failure()
        uses: linc-technologies/.github/.github/actions/slack_notify@master
        continue-on-error: true
        with:
          event: build
          success: success()
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
