name: "Go Module"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
          cache: true

      - name: "Git HTTPS"
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      - name: "Setup Mongo"
        if: github.event.repository.name != 'finance'
        uses: linc-technologies/.github/.github/actions/service_mongo@feature/composite

      - name: "Go Test"
        run: go test -vet=off -tags internal -v ./...

      - name: "Slack Notify"
        if: success() || failure()
        uses: linc-technologies/.github/.github/actions/slack_notify@feature/composite
        with:
          event: build
          success: success()
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
