name: "Go Module"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.18", "1.19" ]
    steps:

      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v3

      - name: "Setup Go"
        id: setup_go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }} # The Go version to download (if necessary) and use.
          cache: true

      - name: "Format"
        id: format
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: "Lint"
        # TODO: Expand to the other modules once proven / rectified
        if: github.event.repository.name == 'go-wonde'
        id: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: "Git HTTPS"
        id: git_https
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      - name: "Setup Mongo"
        id: setup_mongo
        if: github.event.repository.name == 'go-helpers'
        uses: linc-technologies/.github/.github/actions/service_mongo@master

      - name: "Go Test"
        id: go_test
        run: go test -vet=off -tags internal -v ./...

      - name: "Slack Notify"
        if: success() || failure()
        uses: linc-technologies/.github/.github/actions/slack_notify@master
        continue-on-error: true
        with:
          event: build
          success: ${{ !contains(steps.*.outcome, 'failure') }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
