name: "Go Module"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.19", "1.20" ]
    steps:

      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v3
      
      - name: "Git HTTPS"
        id: git_https
        uses: linc-technologies/.github/.github/actions/git_http@master
        with:
          pat: ${{ secrets.CICD_TOKEN }}

      - name: "Setup Go"
        id: setup_go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }} # The Go version to download (if necessary) and use.
          cache: true

      - name: "Format"
        id: format
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: "Lint"
        id: lint
        uses: golangci/golangci-lint-action@v3
        env:
          GOPRIVATE: github.com/linc-technologies
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.52
          # https://golangci-lint.run/usage/configuration/#command-line-options
          args: --issues-exit-code=0 --build-tags=internal --go=${{ matrix.go }} --timeout=2m --verbose

      - name: "Setup Mongo"
        id: setup_mongo
        if: github.event.repository.name == 'go-helpers'
        uses: linc-technologies/.github/.github/actions/service_mongo@master

      - name: "Go Test"
        id: go_test
        run: go test -vet=off -tags internal -v ./...

      - name: "Slack Notify"
        if: success() || failure()
        uses: linc-technologies/.github/.github/actions/slack_notify@master
        continue-on-error: true
        with:
          event: build
          success: ${{ !contains(steps.*.conclusion, 'failure') }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  iiiii:
    if: ${{ always() }}
    needs: [build]
    uses: ./.github/workflows/validate.yml
    with:
      jobs: ${{ toJSON(needs.*.result) }}
